name: ThemeLandCraft2.0
version: 0.3 Alpha
main: nl.justspooky.tlc.Startup
author: Kevin Wilmsen
website: http:/www.kevinwilmsen.nl
description: Server core voor themelandcraft.

commands:
  themelandcraft:
    description: Main commands
    aliases: [tlc]
  website:
    description: Website command!
    aliases: [web]
  resourcepack:
    description: Download ons resourcepack
    aliases: [rp]
